"""Render the ComfyUI Model Downloader master logo.

The mark is a geometric monogram "M" whose right leg extends into a downward
arrow, fusing the brand initial with the product action ("download model").
Brand-aligned to the dark engineering-console palette already used by the web
UI (--bg-0 / --fg-0 / --ac).

Output: assets/logo-master.png  (1024 x 1024, transparent bg)

Variants and the .iconset / .icns pipeline that depends on this master are
generated by the companion script ``scripts/build_assets.py``.
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

# Brand tokens — kept in sync with comfy_model_downloader/web/styles.css
BG = (14, 17, 22, 0)        # transparent
FG = (231, 238, 246, 255)   # --fg-0
AC = (92, 200, 216, 255)    # --ac
AC_HI = (127, 216, 229, 255)
INK = (11, 16, 21, 255)     # --ac-ink

SIZE = 1024


def _draw_mark(draw: ImageDraw.ImageDraw, size: int) -> None:
    """Draw the monogram-with-arrow at the given canvas size.

    Geometry is normalised to the canvas so the mark scales cleanly; the arrow
    joins the M at the right-inner foot and points down — single continuous
    silhouette, no separate floating chevron glued on top.
    """
    s = size / 1024.0  # scale factor relative to design canvas
    stroke = max(int(round(64 * s)), 2)
    line_join = "miter"

    # The M occupies the upper two thirds of the canvas; the arrow extends
    # from the right-inner foot of the M down into the lower third.
    # Coordinates are design-space (1024x1024); multiply by s.
    m_top = int(180 * s)
    m_bot = int(620 * s)
    m_left = int(170 * s)
    m_right = int(854 * s)
    mid_x = int(512 * s)

    # 5 vertices of the M: left foot, left apex, mid valley, right apex,
    # right foot. Stroke connects: left foot -> left apex -> mid valley ->
    # right apex -> right foot.
    left_foot = (m_left, m_bot)
    left_apex = (m_left + int(80 * s), m_top)
    mid_valley = (mid_x, int(m_top + 240 * s))
    right_apex = (m_right - int(80 * s), m_top)
    right_foot = (m_right, m_bot)

    # Arrow continues from right_foot straight down to arrow tip.
    arrow_tip = (m_right, int(880 * s))
    # Arrowhead: two short strokes angled back toward the shaft.
    head_len = int(110 * s)
    head_w = int(95 * s)
    head_left = (m_right - head_w, arrow_tip[1] - head_len)
    head_right = (m_right + head_w, arrow_tip[1] - head_len)

    # Draw M (foreground)
    draw.line(
        [left_foot, left_apex, mid_valley, right_apex, right_foot],
        fill=FG,
        width=stroke,
        joint=line_join,
    )

    # Draw arrow shaft in foreground, then re-draw the head in accent color
    # so the tip reads as the "drop landing here" cue.
    draw.line(
        [right_foot, arrow_tip],
        fill=FG,
        width=stroke,
    )
    # Arrowhead — two diagonal strokes meeting at the tip
    draw.line(
        [head_left, arrow_tip, head_right],
        fill=AC,
        width=stroke,
        joint=line_join,
    )


def render_master(out_path: Path) -> None:
    img = Image.new("RGBA", (SIZE, SIZE), BG)
    draw = ImageDraw.Draw(img)
    _draw_mark(draw, SIZE)
    img.save(out_path, format="PNG", optimize=True)


if __name__ == "__main__":
    out = Path(__file__).resolve().parent / "logo-master.png"
    render_master(out)
    print(f"master logo written: {out}")